//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.21 at 09:44:47 AM CEST 
//


package de.gbv.ws.daia;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for item complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="item">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="message" type="{http://ws.gbv.de/daia/}message" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://ws.gbv.de/daia/}label" minOccurs="0"/>
 *         &lt;element ref="{http://ws.gbv.de/daia/}department" minOccurs="0"/>
 *         &lt;element ref="{http://ws.gbv.de/daia/}storage" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="available">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;extension base="{http://ws.gbv.de/daia/}availability">
 *                   &lt;attribute name="delay">
 *                     &lt;simpleType>
 *                       &lt;union memberTypes=" {http://www.w3.org/2001/XMLSchema}duration">
 *                         &lt;simpleType>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                             &lt;pattern value="unknown"/>
 *                           &lt;/restriction>
 *                         &lt;/simpleType>
 *                       &lt;/union>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                 &lt;/extension>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="unavailable">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;extension base="{http://ws.gbv.de/daia/}availability">
 *                   &lt;attribute name="expected">
 *                     &lt;simpleType>
 *                       &lt;union memberTypes=" {http://www.w3.org/2001/XMLSchema}date {http://www.w3.org/2001/XMLSchema}dateTime">
 *                         &lt;simpleType>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                             &lt;pattern value="unknown"/>
 *                           &lt;/restriction>
 *                         &lt;/simpleType>
 *                       &lt;/union>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                   &lt;attribute name="queue" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;/extension>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="part" type="{http://ws.gbv.de/daia/}partType" />
 *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "item", propOrder = {
    "message",
    "label",
    "department",
    "storage",
    "availableOrUnavailable"
})
public class Item {

    protected List<Message> message;
    protected Label label;
    protected SimpleElement department;
    protected SimpleElement storage;
    @XmlElements({
        @XmlElement(name = "available", type = Item.Available.class),
        @XmlElement(name = "unavailable", type = Item.Unavailable.class)
    })
    protected List<Availability> availableOrUnavailable;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anyURI")
    protected String id;
    @XmlAttribute(name = "part")
    protected String part;
    @XmlAttribute(name = "href")
    @XmlSchemaType(name = "anyURI")
    protected String href;

    /**
     * Gets the value of the message property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the message property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Message }
     * 
     * 
     * @return Value of the message property.
     */
    public List<Message> getMessage() {
        if (message == null) {
            message = new ArrayList<>();
        }
        return this.message;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link Label }
     *     
     */
    public Label getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link Label }
     *     
     */
    public void setLabel(Label value) {
        this.label = value;
    }

    /**
     * Gets the value of the department property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleElement }
     *     
     */
    public SimpleElement getDepartment() {
        return department;
    }

    /**
     * Sets the value of the department property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleElement }
     *     
     */
    public void setDepartment(SimpleElement value) {
        this.department = value;
    }

    /**
     * Gets the value of the storage property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleElement }
     *     
     */
    public SimpleElement getStorage() {
        return storage;
    }

    /**
     * Sets the value of the storage property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleElement }
     *     
     */
    public void setStorage(SimpleElement value) {
        this.storage = value;
    }

    /**
     * Gets the value of the availableOrUnavailable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the availableOrUnavailable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAvailableOrUnavailable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Item.Available }
     * {@link Item.Unavailable }
     * 
     * 
     * @return Value of the availableOrUnavailable property.
     */
    public List<Availability> getAvailableOrUnavailable() {
        if (availableOrUnavailable == null) {
            availableOrUnavailable = new ArrayList<>();
        }
        return this.availableOrUnavailable;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the part property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPart() {
        return part;
    }

    /**
     * Sets the value of the part property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPart(String value) {
        this.part = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://ws.gbv.de/daia/}availability">
     *       &lt;attribute name="delay">
     *         &lt;simpleType>
     *           &lt;union memberTypes=" {http://www.w3.org/2001/XMLSchema}duration">
     *             &lt;simpleType>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                 &lt;pattern value="unknown"/>
     *               &lt;/restriction>
     *             &lt;/simpleType>
     *           &lt;/union>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Available
        extends Availability
    {

        @XmlAttribute(name = "delay")
        protected String delay;

        /**
         * Gets the value of the delay property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDelay() {
            return delay;
        }

        /**
         * Sets the value of the delay property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDelay(String value) {
            this.delay = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://ws.gbv.de/daia/}availability">
     *       &lt;attribute name="expected">
     *         &lt;simpleType>
     *           &lt;union memberTypes=" {http://www.w3.org/2001/XMLSchema}date {http://www.w3.org/2001/XMLSchema}dateTime">
     *             &lt;simpleType>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                 &lt;pattern value="unknown"/>
     *               &lt;/restriction>
     *             &lt;/simpleType>
     *           &lt;/union>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="queue" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Unavailable
        extends Availability
    {

        @XmlAttribute(name = "expected")
        protected String expected;
        @XmlAttribute(name = "queue")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger queue;

        /**
         * Gets the value of the expected property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExpected() {
            return expected;
        }

        /**
         * Sets the value of the expected property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExpected(String value) {
            this.expected = value;
        }

        /**
         * Gets the value of the queue property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getQueue() {
            return queue;
        }

        /**
         * Sets the value of the queue property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setQueue(BigInteger value) {
            this.queue = value;
        }

    }

}
