/*
 * 2015 Leipzig University Library, http://www.ub.uni-leipzig.de
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * http://opensource.org/licenses/gpl-3.0.html GNU General Public License
 */

/*
    This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
    See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
    Any modifications to this file will be lost upon recompilation of the source schema. 
    Generated on: 2014.05.21 at 09:44:47 AM CEST
*/

package de.gbv.ws.daia;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.gbv.ws.daia package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Department_QNAME = new QName("http://ws.gbv.de/daia/", "department");
    private final static QName _Item_QNAME = new QName("http://ws.gbv.de/daia/", "item");
    private final static QName _Daia_QNAME = new QName("http://ws.gbv.de/daia/", "daia");
    private final static QName _Limitation_QNAME = new QName("http://ws.gbv.de/daia/", "limitation");
    private final static QName _Storage_QNAME = new QName("http://ws.gbv.de/daia/", "storage");
    private final static QName _Institution_QNAME = new QName("http://ws.gbv.de/daia/", "institution");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.gbv.ws.daia
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link SimpleElement }
     * 
     */
    public SimpleElement createSimpleElement() {
        return new SimpleElement();
    }

    /**
     * Create an instance of {@link Label }
     * 
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link Daia }
     * 
     */
    public Daia createDaia() {
        return new Daia();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link Availability }
     * 
     */
    public Availability createAvailability() {
        return new Availability();
    }

    /**
     * Create an instance of {@link Item.Available }
     * 
     */
    public Item.Available createItemAvailable() {
        return new Item.Available();
    }

    /**
     * Create an instance of {@link Item.Unavailable }
     * 
     */
    public Item.Unavailable createItemUnavailable() {
        return new Item.Unavailable();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.gbv.de/daia/", name = "department")
    public JAXBElement<SimpleElement> createDepartment(SimpleElement value) {
        return new JAXBElement<SimpleElement>(_Department_QNAME, SimpleElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Item }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.gbv.de/daia/", name = "item")
    public JAXBElement<Item> createItem(Item value) {
        return new JAXBElement<Item>(_Item_QNAME, Item.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Daia }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.gbv.de/daia/", name = "daia")
    public JAXBElement<Daia> createDaia(Daia value) {
        return new JAXBElement<Daia>(_Daia_QNAME, Daia.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.gbv.de/daia/", name = "limitation")
    public JAXBElement<SimpleElement> createLimitation(SimpleElement value) {
        return new JAXBElement<SimpleElement>(_Limitation_QNAME, SimpleElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.gbv.de/daia/", name = "storage")
    public JAXBElement<SimpleElement> createStorage(SimpleElement value) {
        return new JAXBElement<SimpleElement>(_Storage_QNAME, SimpleElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.gbv.de/daia/", name = "institution")
    public JAXBElement<SimpleElement> createInstitution(SimpleElement value) {
        return new JAXBElement<SimpleElement>(_Institution_QNAME, SimpleElement.class, null, value);
    }

}
